apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  credentials: RfYWNjDJRTlZC3c19hY2Nlc3Nfa2V5X2lkPUFLSUFYQzNQWFlWRElOUDJRTlZCCmF3c19zZWNyZXRfYWNjZXNzX2tleT1nMEtEdkwyYUtSSno2L3lnOEVwYW1NR2RrUlpXWVhaamdpSlV2dkRH
 
